config/routes.rb
Rails.application.routes.draw do

  root "stores#index"
  resources :stores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.js   { @current_item = @store }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { }
        # format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.js   { @current_item = @store }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:title, :des, :address, :phone, :owner)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleapi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<%= form_with(model: store, remote: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: 'control-label' %>
    <%= form.text_field :title, id: :store_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :des, class: 'control-label' %>
    <%= form.text_field :des, id: :store_des, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address, class: 'control-label' %>
    <%= form.text_field :address, id: :store_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone, class: 'control-label' %>
    <%= form.number_field :phone, id: :store_phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :owner, class: 'control-label' %>
    <%= form.text_field :owner, id: :store_owner, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "更新資料" %>
  </div>
<% end %>

app/views/stores/_modal.html.erb
<div class="modal-content">
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"><%= @store.title %></h4>
  </div>
  <div class="modal-body">
    <%= render 'form', store: @store %>
  </div>

</div>

app/views/stores/create.js.erb
console.log('create js')

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Stores</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'New Store', new_store_path, class: 'btn btn-info pull-right' %>
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Des</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Owner</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @stores.each do |store| %>
            <tr>
              <td><%= store.title %></td>
              <td><%= store.des %></td>
              <td><%= store.address %></td>
              <td><%= store.phone %></td>
              <td><%= store.owner %></td>
              <td><%= link_to 'Show', store_path(store), remote: true %></td>
              <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div id="user-modal" class="modal fade generic-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document"></div>
</div>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @store.title %>
</p>

<p>
  <strong>Des:</strong>
  <%= @store.des %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @store.owner %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>

app/views/stores/show.js.erb
$('#user-modal .modal-dialog').html("<%= j render 'modal' %>");
$("#user-modal").modal({
  keyboard: false
});

app/views/stores/update.js.erb
$("#user-modal").modal('toggle');

// window.location = '<%= stores_path %>'


$(document).on('page:update',function(){

    $('form').on('ajax:beforeSend', function(event, xhr, settings) {
        console.log('ajax:beforeSend');
        console.log(event);
        console.log(xhr);
        console.log(settings);
    });
    
    $('form').on('ajax:success', function(event, data, status, xhr) {
        console.log('ajax:success');
        console.log(event);
        console.log(data);
        console.log(status);
        console.log(xhr);
    });
    
    $('form').on('ajax:complete', function(event, xhr, status) {
        console.log('ajax:complete');
        console.log(event);
        console.log(xhr);
        console.log(status);
    });

    $('form').on('ajax:error', function(event, xhr, status, error) {
        console.log('ajax:error');
        console.log(event);
        console.log(xhr);
        console.log(status);
        console.log(error);
    });
});